### ISSUE TITLE
Bug: "Unknown" when I click with mouse sometimes

### ISSUE THREAD

**Issue by Lesnock** [hudy9x/keyreader#2]
Hello!  

keyreader was working just fine, but today, something weird is happening...

Sometimes, when I click with the mouse, "Unknown(202)" appears in the display:

![image](https://github.com/hudy9x/keyreader/assets/19783675/8c42d683-b51b-40d0-92f1-bd7ea0a7db2b)

**Comment by hudy9x** [comment]
Hi @Lesnock 
Thanks for your report

I think this bug caused by rdev - the package i used to listen changes from keyboard, mouse
Unfortunately, as i know, rdev only responses what it listened and do nothing else
That means you have to custom rdev code :(

For now, my rust skill is not good to fix the issue
Apologize for not being able to help you with this
